// auto-generated by get-my-vocadb-java-model at 2020-12-19T03:10:29.8228468
package mikufan.cx.vvd.common.vocadb.model;

import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.ToString;
import lombok.experimental.FieldDefaults;
import lombok.extern.jackson.Jacksonized;

@Getter @ToString
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@Builder(toBuilder = true) @Jacksonized
public final class Album {

   String additionalNames;
   String artistString;
   String coverPictureMime;
   String createDate;
   boolean deleted;
   String discType;
   int id;
   String name;
   double ratingAverage;
   int ratingCount;
   OptionalDateTime releaseDate;
   ReleaseEventForApi releaseEvent;
   String status;
   int version;

}
