// auto-generated by get-my-vocadb-java-model at 2020-12-18T02:33:31.8651341
package mikufan.cx.vvd.common.vocadb.model;

import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.ToString;
import lombok.experimental.FieldDefaults;
import lombok.extern.jackson.Jacksonized;

@Getter @ToString
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@Builder(toBuilder = true) @Jacksonized
public final class ReleaseEvent {

   String additionalNames;
   String category;
   boolean customName;
   String date;
   boolean deleted;
   String description;
   String endDate;
   boolean hasVenueOrVenueName;
   int id;
   String inheritedCategory;
   String name;
   String pictureMime;
   ReleaseEventSeries series;
   SongListBase songList;
   String status;
   String urlSlug;
   Venue venue;
   String venueName;
   int version;

}
