// auto-generated by get-my-vocadb-java-model at 2020-12-19T03:10:29.8597489
package mikufan.cx.vvd.common.vocadb.model;

import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.ToString;
import lombok.experimental.FieldDefaults;
import lombok.extern.jackson.Jacksonized;

import java.util.List;

@Getter @ToString
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@Builder(toBuilder = true) @Jacksonized
public final class ReleaseEventSeries {

   String additionalNames;
   String category;
   boolean deleted;
   String description;
   int id;
   String name;
   String pictureMime;
   String status;
   String urlSlug;
   int version;
   List<WebLink> webLinks;

}
