// auto-generated by get-my-vocadb-java-model at 2020-12-19T03:10:29.269325
package mikufan.cx.vvd.common.vocadb.api.common;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.ToString;
import lombok.experimental.FieldDefaults;
import lombok.experimental.SuperBuilder;
import lombok.extern.jackson.Jacksonized;

import java.util.List;

@Getter @ToString
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@SuperBuilder(toBuilder = true) @Jacksonized
public class PartialFindResult<T> {

   List<T> items;
   String term;
   int totalCount;

}
