# application setting

io: # input, output, and error output dir, can be relative path from the terminal current directory
  input-directory:
  output-directory:
  error-directory:

config: # configuration
  preference:
    # your order of which PV service is preferred if available
    # you can also disable song PV services by not listing them
    # values here are comma separated, name must be same as the pv service string in VocaDB pv json, see VocaDB APIs documentation
    # currently we only support NicoNicoDouga, Youtube and Bilibili
    pv-preference: NicoNicoDouga, Youtube, Bilibili
    # maximum retry before call it a failure, this does not include the first try
    max-retry-count: 2
    # if PVs from one PV service, either original or reprinted, failed to be download,
    # should we move to next available PV service listed in the pv-preference, default value is false
    try-next-pv-service: false
    # if the original PV is unavailable, should we try reprinted PV?
    try-reprinted-pv: true
    # if try-reprinted-pv is true, should we only try reprinted PV after all original PVs are failed?
    # if this setting is false, reprinted pv in the same pv service will be tried before moving to next available pv service
    # if try-reprinted-pv is false, nothing happens
    try-reprinted-only-after-original-pv: true

  # which PV service uses which downloader(s), separated by comma
  # downloader names must be same as names in downloader setting
  # when new PV service is added, change it on DownloaderBaseConfig
  enablement:
    NicoNicoDouga:
    Youtube:
    Bilibili:


  downloader:
    NicoNicoDouga:
      youtube-dl:
        launch-cmd:
        external-args:

      nndownload:
        launch-cmd:
        external-args:

    Youtube:
      youtube-dl:
        launch-cmd:
        external-args:

    Bilibili:
      youtube-dl:
        launch-cmd:
        external-args:




# spring setting

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    serialization:
      indent-output: true
    # default-property-inclusion: non_null # disabling for now, we want 3rd app read our json easily


logging:
  level:
    mikufan: debug