# application setting

downloader:
  io: # input and output dir, can be relative path from the terminal current directory
    input-directory:
    output-directory:

  config:
    pv-preference:
      - NicoNicoDouga
      - Youtube
      - Bilibili

    # which website use which config
    enablement:

    nico-pure-youtube-dl:
      youtube-dl-path:
      youtube-dl-options:
        -v:
        --http-chunk-size: 15M

    youtube:
      youtube-dl-path:
      # to get high quality youtube video,
      # we need to download have ffmpeg for youtube-dl to use it
      ffmpeg-path:
      youtube-dl-options:
        -v:

# spring setting

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true

logging:
  level:
    mikufan: debug
