# this is just a test environment for bypassing validation check
downloader:
  io: # input and output dir, can be relative path from the terminal current directory
    # in test case, resources folder src/test/resources/ is also our base directory
    input-directory: 2019年V家新曲-测试用
    output-directory: dsa

  config:

    nico-pure-youtube-dl:
      youtube-dl-path: dummy.exe
      youtube-dl-options:
        --username: dummy username


    nico-unsafe-idm-youtube-dl:
      youtube-dl-path: dummy.exe
      idm-path: dummy.exe
      youtube-dl-options:
        -v:

    youtube:
      youtube-dl-path: dummy.exe
      # to get high quality youtube video,
      # we need to download have ffmpeg for youtube-dl to use it
      ffmpeg-path: dummy.exe

    bilibili:
      youtube-dl-path: dummy.exe

# spring setting