# application setting

downloader:
  io: # input and output dir, can be relative path from the terminal current directory
    input-directory:
    output-directory:

  config:

    # must need this duplicate level to enable property validation
    pv-preference:
      # values here are comma separated, name must be same as the pv service string in VocaDB pv json
      preference: NicoNicoDouga, Youtube, Bilibili

    # which website use which config
    enablement:
      map:
        # value can be any string, as long as downloader decider part is line up
        NicoNicoDouga: nico-pure-youtube-dl
        Youtube: youtube
        Bilibili: bilibili

    nico-pure-youtube-dl:
      youtube-dl-path:
      youtube-dl-options:
        -v:
        --http-chunk-size: 15M

    nico-unsafe-idm-youtube-dl:
      youtube-dl-path:
      idm-path:
      youtube-dl-options:
        -v:

    youtube:
      youtube-dl-path:
      # to get high quality youtube video,
      # we need to download have ffmpeg for youtube-dl to use it
      ffmpeg-path:
      youtube-dl-options:
        -v:

    bilibili:
      youtube-dl-path:
      youtube-dl-options:
        -v:

# spring setting

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true

logging:
  level:
    mikufan: debug
