# application setting


io: # input, output, and error output dir, can be relative path from the terminal current directory
  input-directory:
  output-directory:
  error-directory:

config:

  # must need this duplicate level to enable property validation
  # TODO: consider use spring Java configuration to remove duplicate level
  pv-preference:
    # values here are comma separated, name must be same as the pv service string in VocaDB pv json
    preference: NicoNicoDouga, Youtube, Bilibili

  # which website use which config
  enablement:
    map:
      # value can be any string, as long as downloader decider part is line up
      NicoNicoDouga: nico-pure-youtube-dl
      Youtube: youtube
      Bilibili: bilibili

  mechanism:
    # this count number doesn't include initial attempt
    max-allowed-retry-count: 3

  downloader:

    # downloading niconico video using youtube-dl only
    # discourage to use the official youtube-dl due to heartbeat problem
    # recommend to use either https://github.com/tsukumijima/youtube-dl or https://github.com/animelover1984/youtube-dl
    nico-pure-youtube-dl:
      youtube-dl-path:
      youtube-dl-options:
        -v:

    # a way faster but will fail if download time exceed 2 minutes due to heartbeat problem
    # this use youtube-dl to retrieve the download url and use IDM to trigger the download
    # only available for window os, and required IDM properly installed (cracked IDM may cause undefined behavior)
    nico-unsafe-idm-youtube-dl:
      youtube-dl-path:
      idm-path:
      youtube-dl-options:
        -v:

    # download youtube video using youtube-dl
    youtube:
      youtube-dl-path:
      # to get high quality youtube video, we need to download with ffmpeg
      ffmpeg-path:
      youtube-dl-options:
        -v:

    # download bilibili video using youtube-dl
    bilibili:
      youtube-dl-path:
      youtube-dl-options:
        -v:

# spring setting

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    serialization:
      indent-output: true


logging:
  level:
    mikufan: debug
