version: '3.7'

services:
  base:
    image: vvd-env
    container_name: vvd-base
    build:
      context: .
      dockerfile: env-setup.Dockerfile
    volumes:
      - ../:/vvd
      # can't use relative path so have to use /root/.m2
      - ~/.m2:/root/.m2 
    working_dir: /vvd
