// auto-generated by get-my-vocadb-java-model at 2020-12-17T22:35:44.8159686
package mikufan.cx.vvd.common.entity;

import lombok.Builder;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

@Getter @ToString
@Builder @Jacksonized
public class Album {

  private String additionalNames;

  private String artistString;

  private String coverPictureMime;

  private String createDate;

  private boolean deleted;

  private String discType;

  private int id;

  private String name;

  private double ratingAverage;

  private int ratingCount;

  private OptionalDateTime releaseDate;

  private ReleaseEvent releaseEvent;

  private String status;

  private int version;

}
