// auto-generated by get-my-vocadb-java-model at 2020-12-18T01:55:55.9588242
package mikufan.cx.vvd.common.entity;

import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.ToString;
import lombok.experimental.FieldDefaults;
import lombok.extern.jackson.Jacksonized;

@Getter @ToString
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@Builder(toBuilder = true) @Jacksonized
public final class Album {

   String additionalNames;

   String artistString;

   String coverPictureMime;

   String createDate;

   boolean deleted;

   String discType;

   int id;

   String name;

   double ratingAverage;

   int ratingCount;

   OptionalDateTime releaseDate;

   ReleaseEvent releaseEvent;

   String status;

   int version;

}
