// auto-generated by get-my-vocadb-java-model at 2020-12-17T22:35:44.8468854
package mikufan.cx.vvd.common.entity;

import lombok.Builder;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

@Getter @ToString
@Builder @Jacksonized
public class Artist {

  private String additionalNames;

  private String artistType;

  private boolean deleted;

  private int id;

  private String name;

  private String pictureMime;

  private String releaseDate;

  private String status;

  private int version;

}
