// auto-generated by get-my-vocadb-java-model at 2020-12-17T22:35:44.8299294
package mikufan.cx.vvd.common.entity;

import lombok.Builder;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

@Getter @ToString
@Builder @Jacksonized
public class EntryThumb {

  private String mime;

  private String urlOriginal;

  private String urlSmallThumb;

  private String urlThumb;

  private String urlTinyThumb;

}
