// auto-generated by get-my-vocadb-java-model at 2020-12-17T22:35:44.8279346
package mikufan.cx.vvd.common.entity;

import lombok.Builder;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

@Getter @ToString
@Builder @Jacksonized
public class LyricsForSong {

  private String cultureCode;

  private int id;

  private String source;

  private String translationType;

  private String url;

  private String value;

}
