// auto-generated by get-my-vocadb-java-model at 2020-12-17T22:35:44.8448913
package mikufan.cx.vvd.common.entity;

import lombok.Builder;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

@Getter @ToString
@Builder @Jacksonized
public class OptionalDateTime {

  private int day;

  private String formatted;

  private boolean isEmpty;

  private int month;

  private int year;

}
