// auto-generated by get-my-vocadb-java-model at 2020-12-18T01:55:55.460156
package mikufan.cx.vvd.common.entity;

import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.ToString;
import lombok.experimental.FieldDefaults;
import lombok.extern.jackson.Jacksonized;

import java.util.List;

@Getter @ToString
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@Builder(toBuilder = true) @Jacksonized
public class PartialFindResult<T> {

  protected List<T> items;

  protected String term;

  protected int totalCount;

}
