// auto-generated by get-my-vocadb-java-model at 2020-12-17T22:35:44.2744131
package mikufan.cx.vvd.common.entity;

import lombok.Builder;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

import java.util.List;

@Getter @ToString
@Builder @Jacksonized
public class PartialFindResult<T> {

  protected List<T> items;

  protected String term;

  protected int totalCount;

}
