// auto-generated by get-my-vocadb-java-model at 2020-12-18T01:55:55.9747821
package mikufan.cx.vvd.common.entity;

import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.ToString;
import lombok.experimental.FieldDefaults;
import lombok.extern.jackson.Jacksonized;

@Getter @ToString
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@Builder(toBuilder = true) @Jacksonized
public final class PV {

   String author;

   int createdBy;

   boolean disabled;

   PVExtendedMetadata extendedMetadata;

   int id;

   int length;

   String name;

   String publishDate;

   String pvId;

   String service;

   String pvType;

   String thumbUrl;

   String url;

}
