// auto-generated by get-my-vocadb-java-model at 2020-12-17T22:35:44.8099827
package mikufan.cx.vvd.common.entity;

import lombok.Builder;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

import java.util.List;

@Getter @ToString
@Builder @Jacksonized
public class Song {

  private String additionalNames;

  private List<Album> albums;

  private List<ArtistForSong> artists;

  private String artistString;

  private String createDate;

  private String defaultName;

  private String defaultNameLanguage;

  private boolean deleted;

  private int favoritedTimes;

  private int id;

  private int lengthSeconds;

  private List<LyricsForSong> lyrics;

  private EntryThumb mainPicture;

  private int mergedTo;

  private String name;

  private List<LocalizedString> names;

  private int originalVersionId;

  private String publishDate;

  private List<PV> pvs;

  private String pvServices;

  private int ratingScore;

  private ReleaseEvent releaseEvent;

  private String songType;

  private String status;

  private List<TagUsage> tags;

  private String thumbUrl;

  private int version;

  private List<WebLink> webLinks;

}
