// auto-generated by get-my-vocadb-java-model at 2020-12-17T22:35:44.8648362
package mikufan.cx.vvd.common.entity;

import lombok.Builder;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

@Getter @ToString
@Builder @Jacksonized
public class TagBase {

  private String additionalNames;

  private String categoryName;

  private int id;

  private String name;

  private String urlSlug;

}
