# application setting

io: # vocadb favourite list id in int, output, and error output dir, can be relative path from the terminal current directory
  input-list-id:
  output-directory:
  error-directory:

config:
  base-url: https://vocadb.net
  # the user agent to be used for calling VocaDB APIs
  user-agent:
  #max number of songs you can fetch from one api request of the vocadb favourite list
  api-page-size: 50
  # maximum amount of song can be processed at the same time
  # if set to < 1, it will be the number of cores
  batch-size: 10

# spring setting
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true # make it compatible to the new vocadb client
    serialization:
      indent-output: true
    # default-property-inclusion: non_null # disabling for now, we want 3rd app read our json easily


logging:
  level:
    mikufan: debug