# application setting

io: # vocadb favourite list id in int, output, and error output dir, can be relative path from the terminal current directory
  input-list-id:
  output-directory:
  error-directory:

config:
  base-url: https://vocadb.net
  user-agent:
  #max number of songs you can fetch from one api request of the vocadb favourite list
  api-page-size: 50
# spring setting

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    serialization:
      indent-output: true


logging:
  level:
    mikufan: debug