# application setting

io: # all fields are required
  # the VocaDB favourite list ID in Int, can be retrieved from URL https://vocadb.net/L/<The ID is here>
  input-list-id:
  # the output directory of this module, can be an absolute path or a relative path from the application current running directory
  output-directory:
  # the error directory of this module, used for reporting errors for debugging, can be an absolute path or a relative path from the application current running directory
  error-directory:

config: # all fields are optional except the user-agent field
  # the base url of VocaDB
  # can change it to https://utaitedb.net if your list is on UtaiteDB, but may some compatibility issues
  base-url: https://vocadb.net
  # the user agent to be used for calling VocaDB APIs, to help VocaDB staff identify this program (see https://github.com/VocaDB/vocadb/wiki/Public-API#api-usage-rules) 
  user-agent:
  # max number of songs you can fetch from one api request of the vocadb favourite list, max is 50
  api-page-size: 50
  # maximum amount of song can be processed at the same time
  # if set to < 1, it will be the number of logical CPU cores
  batch-size: 10

# spring setting, don't touch it unless u know Spring very well
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    serialization:
      indent-output: true
    # default-property-inclusion: non_null # disabling for now, we want 3rd app read our json easily
  config:
    import: optional:file:./my-producer-config.yml,optional:file:./my-producer-config.yaml,optional:file:./my-producer-config.properties

logging:
  level:
    mikufan: info