# application setting


io: # input, output, and error output dir, can be relative path from the terminal current directory
  input-directory:
  output-directory:
  error-directory:

config:
  environment:
    # array of string representing how to launch external programs
    python-launch-script:
    ffmpeg-launch-script:



# spring setting

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    serialization:
      indent-output: true


logging:
  level:
    mikufan: debug