
io: # input, output, and error output dir, can be relative path from the terminal current directory
  input-directory:
  output-directory:
  error-directory:

config: # configuration
  envrionment: # all cmd are list of strings, executed with the root directory of the project as the current directory
    python-launch-cmd:
    ffmpeg-launch-cmd:
    mediainfo-launch-cmd: