
io: # input, output, and error output dir, can be relative path from the terminal current directory
  input-directory:
  output-directory:
  error-directory:

config: # configuration
  environment: # all cmd are list of strings, executed with the root directory of the project as the current directory
    python-launch-cmd:
    ffmpeg-launch-cmd:
    mediainfo-launch-cmd:

  batch:
    batch-size: 0 # number of files to process in parallel, default is 0 which represents # of cores

  process:
    # each process in this module should be run in fairly quick time, even though for a one-hour video, it should be run in less than 5 minutes
    # if you think you need more time, change the setting here
    timeout: 5
    unit: minutes

  preference:
    retry-on-extraction: 3 # number of times to retry on audio extraction error
    retry-on-tagging: 3 # number of times to retry on audio file tagging error


# spring setting, DON't touch. unless you know what you are doing

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    serialization:
      indent-output: true
    # default-property-inclusion: non_null # disabling for now, we want 3rd app read our json easily


logging:
  level:
    mikufan: debug