# application setting


io: # input, output, and error output dir, can be relative path from the terminal current directory
  input-directory: 2019年V家新曲-测试用PV
  output-directory: asd
  error-directory: asd/dsa

config:
  environment:
    # array of string representing how to launch external programs
    python-launch-script: [python]
    ffmpeg-launch-script: [D:\11134\Videos\Vocaloid Coding POC\ffmpeg.exe]



# spring setting

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    serialization:
      indent-output: true


logging:
  level:
    mikufan: debug