# application setting


io: # input, output, and error output dir, can be relative path from the terminal current directory
  input-directory: 2019年V家新曲-测试用PV
  output-directory: asd
  error-directory: asd/dsa

config:
  environment:
    # string representing how to launch external programs
    python-launch-cmd: python
    ffmpeg-launch-cmd: D:\11134\Videos\Vocaloid Coding POC\ffmpeg.exe
