# application setting


io: # input, output, and error output dir, can be relative path from the terminal current directory
  input-directory:
  output-directory:
  error-directory:

config:
  environment:
    # strings representing how to launch external programs
    # can be a single command or the path to a executable file
    # make sure run 'pip install mutagen' first as the python script requires it
    python-launch-cmd:
    ffmpeg-launch-cmd:



# spring setting

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    serialization:
      indent-output: true


logging:
  level:
    mikufan: debug