// auto-generated by get-my-vocadb-java-model at 2020-12-18T01:55:55.9668043
package mikufan.cx.vvd.common.model;

import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.ToString;
import lombok.experimental.FieldDefaults;
import lombok.extern.jackson.Jacksonized;

@Getter @ToString
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@Builder(toBuilder = true) @Jacksonized
public final class LyricsForSong {

   String cultureCode;

   int id;

   String source;

   String translationType;

   String url;

   String value;

}
