// auto-generated by get-my-vocadb-java-model at 2020-12-18T02:33:31.8152677
package mikufan.cx.vvd.common.vocadb.api.songlist.getlist;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.ToString;
import lombok.experimental.FieldDefaults;
import lombok.experimental.SuperBuilder;
import lombok.extern.jackson.Jacksonized;
import mikufan.cx.vvd.common.vocadb.model.Song;

@Getter @ToString
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@SuperBuilder(toBuilder = true) @Jacksonized
public final class SongInList {

   String notes;
   int order;
   Song song;

}
