// auto-generated by get-my-vocadb-java-model at 2020-12-18T02:25:49.7603381
package mikufan.cx.vvd.common.vocadb.api.songlist.getlist;

import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.ToString;
import lombok.experimental.FieldDefaults;
import lombok.extern.jackson.Jacksonized;
import mikufan.cx.vvd.common.vocadb.model.Song;

@Getter @ToString
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@Builder(toBuilder = true) @Jacksonized
public final class SongInList {

   String notes;

   int order;

   Song song;

}
