// auto-generated by get-my-vocadb-java-model at 2020-12-19T03:10:29.8128738
package mikufan.cx.vvd.common.vocadb.api.songlist.getlist;

import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.ToString;
import lombok.experimental.FieldDefaults;
import lombok.extern.jackson.Jacksonized;
import mikufan.cx.vvd.common.vocadb.model.SongForApi;

@Getter @ToString
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@Builder(toBuilder = true) @Jacksonized
public final class SongInListForApi {

   String notes;
   int order;
   SongForApi song;

}
